import type { Metadata } from "next";
import { outfit } from "./fonts";

import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-primary ${outfit.className}`}>
        <main className="flex flex-col justify-center items-center w-full text-third pt-14">
          <Navbar></Navbar>
          {children}
        </main>
      </body>
    </html>
  );
}
